import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col justify-center">
        <div className="flex gap-2 justify-center items-end">
          <Image
            className={""}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <p className={`text-center mt-1 ${inter.className}`}>
          App created with{" "}
          <Link
            href="https://www.npmjs.com/package/next-tailwind-app"
            target="_blank"
            className="underline"
          >
            next-tailwind-app
          </Link>
        </p>
      </main>
    </>
  );
}
